// Static list of unique authors from the songs table — sorted alphabetically (pl locale).
// Regenerate by running: node --input-type=module scripts/fetch-authors.mjs
export const AUTHORS: string[] = [
  "Aad Bosma",
  "Adolf Wetlesen",
  "Aksel J. Smith",
  "Aksel Smith",
  "Albert G. Boek",
  "Albertha T. Eltzholtz",
  "Amalie Holter",
  "Amanda Sandbergh",
  "Amund Fosstvedt",
  "Amy de Jong",
  "Anders Hovden",
  "Anders Jansen",
  "Anders Nilsson d.y",
  "André Wessels",
  "Andreas Bekkevold",
  "Andreas Myhre",
  "Andreas Nilsen",
  "Andrew L. Skoog",
  "Andrew Omondi",
  "Anita Brentnall",
  "Anna B. Warner",
  "Anna Bæklund",
  "Anna Bekkevold",
  "Anna Belden",
  "Anna Bjerkeli",
  "Anna Jonassen",
  "Anna Kjærnet",
  "Anne Reinikainen",
  "Annelise Pehrson",
  "Anni Skreosen",
  "Annie L. W. Coghill",
  "Arild Tombre",
  "Arne Bæklund",
  "Arne Færestrand",
  "Arne Garborg",
  "Arne K. Kristoffersen",
  "Arne Velten",
  "Arthur Smith Arnott",
  "Åshild Olsen",
  "Åshild Opitz",
  "Aslaug Frantzen",
  "August Zachariassen",
  "Berit Hustad Nilsen",
  "Berna Oord-Bols",
  "Bernhard S. Ingemann",
  "Bessie F. Simmins Hatcher",
  "Birger W. Landgraff",
  "Bjarne Gulichsen",
  "Bjørn Fuglset",
  "Bjørnstjerne Bjørnson",
  "Børge Nielsen",
  "Brigitte Richter",
  "Camilla Johansen",
  "Carole Graham",
  "Caroline Klings",
  "Carrie E. Breck",
  "Cecil F. Alexander",
  "Charles H. Gabriel",
  "Charlotte Ditlefsen",
  "Christen Zürcher",
  "Christoph von Schmid",
  "Clare Herbert Woolston",
  "Clarisse Hansen",
  "Claude Kue Kamdem",
  "Colin C. Kerr",
  "Connie Christensen",
  "Cors de Kort",
  "Dagny Bøe",
  "Daniel W. Whittle",
  "Daniela Winther Nilsen",
  "Dany Goossens",
  "Darlene Hamren",
  "David Boussoir",
  "David Evensen",
  "David H. Roth",
  "David Myhre",
  "David Tombre",
  "Dianne Jost",
  "Dini Nooitgedagt-Reesink",
  "Dorothea Albrecht",
  "Douwe J. Muller",
  "Edith Lerstad",
  "Edvin Andersen",
  "Edwin Bekkevold",
  "Egil Andersen",
  "Einar Tombre",
  "Elen O. Bernhoft",
  "Elias Aslaksen",
  "Elias Blix",
  "Elias Evensen",
  "Elihu Pedersen",
  "Elisabeth Eriksen",
  "Elisabeth Jeppesen",
  "Elisabeth Müller",
  "Elise Borst",
  "Elise Gasser",
  "Elise Schøll",
  "Elisha A. Hoffmann",
  "Eliza E. Hewitt",
  "Ellen Bekkevold",
  "Ellida Kjeldsen",
  "Ellinor Bernhardsen",
  "Elsa Eklund",
  "Else Eriksen",
  "Else M. Clausen",
  "Emil Gustafson",
  "Emil Quandt",
  "Emmi Horstmann",
  "Enok Pedersen",
  "Eric M. Bergquist",
  "Erna Pedersen",
  "Ernst Christian Richardt",
  "Ernst Gebhardt",
  "Esther Zürcher",
  "Eugen B. Sørensen",
  "Eva Østgård",
  "Fanny Crosby",
  "Filip Bekkevold",
  "Finn Risa",
  "Frances R. Havergal",
  "Francis Rous",
  "Franklin Edson Belden",
  "Fredrik A. Bloom",
  "Fredrik Slettedal",
  "Friedbert Maier",
  "Friederich H. Ranke",
  "Friedrich Holzwarth",
  "Fru Viggo C. Pettersen",
  "Geoffrey H. Brentnall",
  "Georg Riksfjord",
  "Georg Weissel",
  "George Duffield, Jr.",
  "George S. Railton",
  "Gerd E. Jensen",
  "Gerda Kingo",
  "Gerry Weggeman-ten Kleij",
  "Gjermund C. Frivold",
  "Gjermund Dahl",
  "Gjertrud Stenbrenden",
  "Gjertrud Wehme",
  "Gudbrand Fossnes",
  "Gunnar Bendixen",
  "Gunnar Lindhjem",
  "Gustav Blom",
  "Gustava Kielland",
  "Håkon Johannessen",
  "Halfdan Kamben",
  "Halma Hårseth",
  "Hanna Eriksen",
  "Hans A. Brorson",
  "Hans Kr. Bertelsen",
  "Harm de Jonge",
  "Harry Dickson Loes",
  "Hedvig Hansen",
  "Heidi Drageseth Baumann",
  "Helen P. Simons",
  "Helene Hansen",
  "Helga Moe",
  "Helga Visser-Zwart",
  "Henrik Vestergård",
  "Henry A. Tandberg",
  "Henry Fr. Lyte",
  "Henry Hågen Hansen",
  "Herbert H. Booth",
  "Herman van Dijk",
  "Hermien Steenkamp-van der Linden",
  "Hilda Broks",
  "Hjalmar Hansen",
  "Horatio R. Palmer",
  "Immanuel Solberg",
  "Inez Ferreira",
  "Inger Larsen",
  "Ingrid Bekkevold",
  "Ingrid Corneliussen Harbo",
  "J. A. Reitz",
  "Jaap G. Littooij",
  "Jackie Vannoy",
  "Jacob Uthupp Koshy",
  "Jacqueline Marques",
  "James R. Murray",
  "Jan E. Fjeldstad",
  "Jan Håvard Bratlie",
  "Jan Ottens",
  "Jan-Hein Staal",
  "Janet Lenk",
  "Janneke Visser-Zwart",
  "Jari Reinikainen",
  "Jean W. Hunter",
  "Jelma Baak-Vellinga",
  "Jens Halvorsen",
  "Jens N. L. Schjørring",
  "Jens Reiersrud",
  "Jerry Graham",
  "Johan Hoff",
  "Johan J. Krohn",
  "Johan O. Smith",
  "Johann W. Hey",
  "Johanna Paasila",
  "Johanne Sandvik",
  "Johannes Bekkevold",
  "Johannes Daniel Falk",
  "Johannes Nevanlinna",
  "John Bunyan",
  "John Newton",
  "John Oommen",
  "John Stensland",
  "Johnson Oatman, Jr.",
  "Jonas S. Pettersen",
  "Joop de Wijs",
  "Josef Olsen",
  "Joseph Mohr",
  "Jostein Østmoen",
  "Judith Aslaksen",
  "Julia Seiter",
  "Julia Ward Howe",
  "Julie von Hausmann",
  "Karen Strubhar Janz",
  "Karethe Opitz Mihai",
  "Kari Bratlie",
  "Kari Sundmark",
  "Kari Vange",
  "Karin Jensen",
  "Karin Trinkle",
  "Karina C. Lenk",
  "Karl Birkeland",
  "Karl Martinsen",
  "Karl Pedersen",
  "Karl Tombre",
  "Kjell Fossnes",
  "Kjell Johnsen",
  "Kjell W. Selrod",
  "Knut Nyland",
  "Knut Røhr-Staff",
  "Kristi Kjosås",
  "Kristian Hobbelstad",
  "Kristian Kristiansen",
  "Kristiane Opitz Andersen",
  "Kristin Bårdsen",
  "Kristine Ramdahl",
  "Larry Roth",
  "Lars Håkon Halvorsen",
  "Lars S. Brænden",
  "Lars Schroeder",
  "Laurentze Mørch",
  "Leen Schmal",
  "Len Hines",
  "Leopold Budde",
  "Lewi Pethrus",
  "Liane Fitch",
  "Lina Sandell-Berg",
  "Linea Tangen",
  "Linnea Riis Nilsen",
  "Lise Østermark Larsen",
  "Lorentz Risnes",
  "Lucia Gruppen-Woltinge",
  "Maija-Liisa Liimatainen",
  "Maja Ådalen",
  "Marc Auchet",
  "Marc Smith",
  "Margit Baltzersen",
  "Margrethe Munthe",
  "Mari Clausen",
  "Maria Eisenberg",
  "Maria Elisabeth Olsen",
  "Marianne Steiner-Zürcher",
  "Marie Johansen",
  "Marie Wexelsen",
  "Marit Baardsen",
  "Marit Risnes",
  "Marrie Buter-van der Linden",
  "Martha Irving",
  "Martha Langsholt",
  "Martin Luther",
  "Martinius Madsen",
  "Martti Gerlander",
  "Mary Pedersen",
  "Matthias Richter",
  "Menno van der Staal",
  "Michael Twilley",
  "Mona Telle",
  "Morten Smith",
  "Nellie Talbot",
  "Nelly Weigold",
  "Nikolaj F. S. Grundtvig",
  "Nils J. Holm",
  "Nils Risnes",
  "Nils Trobe",
  "Øivind Jacobsen",
  "Olaug Madsen",
  "Olav Jakobsen",
  "Ole Risa",
  "Ole Skiaker",
  "Ole Skotland",
  "Ole-Petter Andersen",
  "Olette Hovde",
  "Olga Johansen",
  "Olga Olsen",
  "Oline Eriksen",
  "Oliver Tangen",
  "Otto Udd-Johansen",
  "Paul Gerhardt",
  "Pauli Sander",
  "Paulien Wiersma-de Kort",
  "Peter A. Ravnå",
  "Peter Cheetham",
  "Peter Damnjanovic",
  "Petter Dass",
  "Philip P. Bliss",
  "Piet de Lange",
  "Pirjo Törrönen",
  "Ragnhild Backe",
  "Rakel Bratlie",
  "Randi Bovolden",
  "Reidar A. Vedvik",
  "Richard Edhelberg",
  "Richard Jukes",
  "Richard Savage",
  "Rikke Andreassen",
  "Roar Sjemmedal",
  "Robert Lowry",
  "Romain Jacquier",
  "Romkje de Boer",
  "Rosanne Wessels",
  "Roshini Xavier Sacra",
  "Ruben Holm Andersen",
  "Rudolf Schwaiger",
  "Rune Kronstad",
  "Ruth Boer-van der Linden",
  "Ruth Evangelisti",
  "Ruth Gasser",
  "Ruth Marie Schytt",
  "Sadok Risnes",
  "Samia Kobzeff",
  "Sandra Høines",
  "Sarah Hauptkorn",
  "Sherry Dini",
  "Shirley Bailey",
  "Signe Frøland",
  "Sigurd Bratlie",
  "Sigurd Johan Bratlie",
  "Sigvart M. Engeset",
  "Simen Andresen",
  "Solveig Riktor",
  "Sølvi Johansen",
  "Sophia T. Griswold",
  "Stefan Erz",
  "Stefan Runtsch",
  "Stephen Chadwick",
  "Steve Cooper",
  "Susan B. Warner",
  "Susanne Müller",
  "Sverre L. Riksfjord",
  "Sverre Nielsen",
  "Sybille Schradi",
  "Sylvia A. Svensen",
  "Synnøve Lindell",
  "Theo Müller",
  "Theofil Engstrøm",
  "Thomas B. Barratt",
  "Thomas Kingo",
  "Thor Stenseth",
  "Thordis Nyfeldt Huseby",
  "Thore Bjørnstad",
  "Thorleif Hansen",
  "Thorolf Eriksen",
  "Titus Gruppen",
  "Tje Pin Seah",
  "Tore Lindell",
  "Torill Ellefsen",
  "Torleif Bratlie",
  "Torstein Leth",
  "Torstein Skutle",
  "Trude Martinsen",
  "Turid Vedvik",
  "Uwe Schmidt",
  "Valborg Boldvik",
  "Veit Schradi",
  "Vera Yeremeyeva",
  "Vidar Olsen",
  "Werner Schrödter",
  "Wilhelm Berg",
  "William A. Ogden",
  "William James Pearson",
  "Wim J. Mensink",
]
